#!/usr/bin/env node
// Scans src/ for lucide-react icon imports and generates src/icons.tsx with
// only the needed icons as minimal SVG components
import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs'
import { join, resolve, extname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const projectRoot = resolve(__dirname, '..')
const srcDir = join(projectRoot, 'src')
const outFile = join(srcDir, 'icons.tsx')
const lucideEsmDir = join(projectRoot, 'node_modules/lucide-react/dist/esm')

function getAllFiles(dir, exts) {
  const results = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      results.push(...getAllFiles(full, exts))
    } else if (exts.includes(extname(entry))) {
      results.push(full)
    }
  }
  return results
}

const files = getAllFiles(srcDir, ['.tsx', '.ts', '.jsx', '.js'])
const iconNames = new Set()
const importPattern = /import\s+(?:type\s+)?\{([^}]*)\}\s+from\s+['"]lucide-react['"]/g

for (const file of files) {
  if (file === outFile) continue
  const content = readFileSync(file, 'utf-8')
  let match
  while ((match = importPattern.exec(content)) !== null) {
    for (const part of match[1].split(',')) {
      const name = part.trim().replace(/\s+as\s+\w+/, '').trim()
      if (!name || name.startsWith('type ') || name === 'LucideIcon') continue
      iconNames.add(name)
    }
  }
}

console.log(`Found ${iconNames.size} icons: ${[...iconNames].sort().join(', ')}`)

const mainBundle = readFileSync(join(lucideEsmDir, 'lucide-react.js'), 'utf-8')
const nameToFile = {}
const exportLineRe = /export \{([^}]+)\} from '(\.\/icons\/[^']+\.js)'/g
let lineMatch
while ((lineMatch = exportLineRe.exec(mainBundle)) !== null) {
  const filePath = join(lucideEsmDir, lineMatch[2])
  for (const part of lineMatch[1].split(',')) {
    const alias = part.trim().match(/default as (\w+)/)
    if (alias) nameToFile[alias[1]] = filePath
  }
}

function extractNodes(filePath) {
  const src = readFileSync(filePath, 'utf-8')
  const m = src.match(/createLucideIcon\([^,]+,\s*(\[[\s\S]+\])\s*\);/)
  if (!m) return null
  try {
    const parsed = new Function(`return ${m[1]}`)()
    return parsed.map(([tag, { key, ...attrs }]) => [tag, attrs])
  } catch {
    return null
  }
}

const iconEntries = []
const missing = []

for (const name of [...iconNames].sort()) {
  const filePath = nameToFile[name]
  if (!filePath) { missing.push(`${name} (not in bundle)`); continue }
  const nodes = extractNodes(filePath)
  if (!nodes) { missing.push(`${name} (parse failed)`); continue }
  iconEntries.push({ name, nodes })
}

if (missing.length > 0) console.warn('Skipped icons:', missing.join(', '))

function toKebab(name) {
  return name
    .replace(/([A-Z])/g, (_, l, i) => (i === 0 ? '' : '-') + l.toLowerCase())
    .replace(/(\d+)/g, (_, d, i) => (i === 0 ? '' : '-') + d)
    .replace(/-+/g, '-')
}

const iconLines = iconEntries.map(({ name, nodes }) =>
  `export const ${name} = /*#__PURE__*/createIcon('${toKebab(name)}', ${JSON.stringify(nodes)})`
)

const output = `// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit manually
// Run: node scripts/generate-icons.mjs
// SVG data sourced from lucide-react (https://lucide.dev) — ISC License
// Copyright (c) for portions held by Cole Bemis 2013-2022 (Feather, MIT).
// All other copyright (c) Lucide Contributors 2022.
import { createElement, forwardRef } from 'react'
import type { SVGProps } from 'react'

export type LucideProps = Omit<SVGProps<SVGSVGElement>, 'ref'> & {
  size?: number | string
  strokeWidth?: number | string
  absoluteStrokeWidth?: boolean
  color?: string
}

export type LucideIcon = ReturnType<typeof createIcon>

function createIcon(name: string, nodes: [string, Record<string, string | number>][]) {
  const Icon = forwardRef<SVGSVGElement, LucideProps>(
    ({ size = 24, strokeWidth = 2, color, absoluteStrokeWidth, className, ...props }, ref) =>
      createElement(
        'svg',
        {
          ref,
          xmlns: 'http://www.w3.org/2000/svg',
          width: size,
          height: size,
          viewBox: '0 0 24 24',
          fill: 'none',
          stroke: color ?? 'currentColor',
          strokeWidth: absoluteStrokeWidth
            ? (Number(strokeWidth) * 24) / Number(size)
            : strokeWidth,
          strokeLinecap: 'round',
          strokeLinejoin: 'round',
          className: className ? \`lucide lucide-\${name} \${className}\` : \`lucide lucide-\${name}\`,
          ...props,
        },
        ...nodes.map(([tag, attrs], i) => createElement(tag, { key: i, ...attrs }))
      )
  )
  Icon.displayName = name
  return Icon
}

${iconLines.join('\n')}
`

writeFileSync(outFile, output, 'utf-8')
console.log(`Generated src/icons.tsx with ${iconEntries.length} icons`)
